### ISSUE TITLE
textLength XML code in SVG output makes text editing in Inkscape a problem

### ISSUE THREAD

**Issue by svenyos** [r-lib/svglite#118]
A need for an alternative to textLength? SVG output generating by svglite (e.g. ggplot graphs) with fixed textLength entries in their XML code result in corresponding text labels in the file to have fixed lengths. If letters of the text are deleted from these text boxes, the remaining text stretches to fill the space. The reverse is true for entering extra text.   Removing the textLength entries in the XML code fixes the problem

**Comment by hyokangs** [comment]
May be a related issue: when I import svg files to MS Word, text widths (or spaces between them) does not show correctly. Web browsers show them correctly, though.
![image](https://user-images.githubusercontent.com/34936244/87204292-4f190700-c2b9-11ea-85f4-118aecf606e0.png)

**Comment by thomasp85** [comment]
@hyokangs yeah, word is horrible at rendering svgs - I don't think there is anything we can do about that

@svenyos I understand the issue but since we cannot predict how wide a text string is in different renders and the graphic engine uses the string width to position text we need a way to fix the width... I have a few ideas to fix this for standard alignment but I'm not sure it can be fixed generally

**Comment by svenyos** [comment]
Fair enough. For anyone encountering this issue, one work around is replacing the term "textLength" to something unintelligible so that inkscape ignores it (by opening the SVG file in a text or XML editor and editing XML code directly). This removes the length constraint on text when rendered in inkscape. Not elegant but effective.

**Comment by thomasp85** [comment]
I added a switch in the commit that closed this
