### ISSUE TITLE
`geom_rect` disappears when saving plot

### ISSUE THREAD

**Issue by emstruong** [r-lib/svglite#160]
Related to [ggplot2::ggsave](https://github.com/tidyverse/ggplot2/issues/5121).

# Code

``` r
library(ggplot2)
library(svglite)

set.seed(123)

df <-
  data.frame(
    x = rpois(300, 3),
    y = c(rbinom(100, 1, .3), rbinom(100, 1, .5), rbinom(100, 1, .7)),
    group = factor(rep(c("a", "b", "c"), each = 100)) 
  )

loghistGraph<-ggplot(df, aes(xmin = x, xmax = x, ymin = rep(0, nrow(df)), ymax = rep(nrow(df)), color = group)) +
    geom_rect(size = 4, position = position_dodge(.3))


# Works
grDevices::svg("DefaultSvgWorks.svg")
print(loghistGraph)
dev.off()
#> png 
#>   2

# Doesn't work
svglite("svgliteBug.svg")
print(loghistGraph)
dev.off()
#> png 
#>   2
```

<sup>Created on 2022-12-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Attached are the two plots I get

Using `svg()`
![DefaultSvgWorks](https://user-images.githubusercontent.com/112967876/209587421-8b97bde9-7487-4e3d-b80c-8b0c1b7c3fdf.svg)

Using `svglite()`
![svgliteBug](https://user-images.githubusercontent.com/112967876/209587424-b8695417-f7b7-40bd-8a62-15fb54ce7dc8.svg)

**Comment by thomasp85** [comment]
If you open the svg file you can see that it contains the requested rects as expected. My guess is that because you are plotting rects with 0 width some sag renderers decide to not show these irrespective of whether they have a stroke. That is not the fault of svglite, though. The `svg()` device doesn't have this because it encodes everything as a path meaning that renderers can't make these optimisations.
