### ISSUE TITLE
Saved svg size does not correspond to specified

### ISSUE THREAD

**Issue by suvarzz** [r-lib/svglite#90]
Hello!
Svglite is a very useful package.
For some reasons saved SVG has 4x4 inches instead of 5x5 when it is opened in Inkscape.
```
svglite("~/Desktop/test.svg", height=5, width=5)
x <- c(1, 2, 3, 4, 5)
y <- c(1, 2, 4, 3, 2)
plot(x~y)
dev.off()
```
System: Ubuntu 16.04 (x86_64-pc-linux-gnu)
RStudio: Version 1.0.136
R version 3.3.2 (2016-10-31)
Inkscape: 0.91

Best wishes!

**Comment by drewmjohnston** [comment]
I similarly am having problems with this--I get different aspect ratios when using the same height/width and exporting as png vs svg. Svglite doesn't seem to respect the aspect ratio provided in the same way that the png export tool does.

**Comment by bwiernik** [comment]
The aspect ratio is also not respected when inserting an svglite svg into Microsoft Office. The svg produced `svg` or `Cairo::CairoSVG` render with the correct aspect ratio.

Here is how an svglite SVG gets rendered by Office
![image](https://user-images.githubusercontent.com/4773225/74041342-7af33200-4993-11ea-93d9-77318fa779af.png)

Here is how an svg SVG gets rendered by Office
![image](https://user-images.githubusercontent.com/4773225/74041601-f523b680-4993-11ea-8e67-1b91e9a72841.png)

The 3 svg files from the different devices are attached.
[svglite.svg.txt](https://github.com/r-lib/svglite/files/4171517/svglite.svg.txt)
[cairoSVG.svg.txt](https://github.com/r-lib/svglite/files/4171515/cairoSVG.svg.txt)
[svg.svg.txt](https://github.com/r-lib/svglite/files/4171516/svg.svg.txt)

**Comment by xgirouxb** [comment]
I also have this issue, I would love for this to work because svglite seems to be the only graphics device that exports svg files with text as proper text objects instead of glyphs, which really simplifies post processing using software like Inkscape. As a workaround, I've been multiplying all my units by 4/3 which seems to result in the desired dimensions so far.

**Comment by thomasp85** [comment]
@bwiernik can I get you to check that #90 fixes your issue as well?

**Comment by bwiernik** [comment]
It fixes the aspect ratio issue, yes. But there still seems to be an unrelated issue rendering the axis labels text. See the attached Word document showing an svglite svg having all of the y axis labels kerned and aligned improperly, whereas the svg svg is correct:
[svg_office_rendering.docx](https://github.com/r-lib/svglite/files/4752938/svg_office_rendering.docx)

Let me know if you'd like this in a new issue.

**Comment by thomasp85** [comment]
This is def another issue. That being said, I suspect that word just is horrible for rendering svg... (see below)

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/1775316/84165367-e8af8780-aa73-11ea-9775-1fcf3abac8b5.png">

The text rendering is undergoing changes anyway, so it may get fixed with #101 (but not necessarily)

**Comment by bwiernik** [comment]
Yeah, svg svg's frequently lose the text size information like that on save, though they look fine when first inserted 
![image](https://user-images.githubusercontent.com/4773225/84166531-06b0c400-aa43-11ea-8ce9-b37eb60e7c07.png)

Weird that the svglite one looks fine on Mac.

**Comment by thomasp85** [comment]
svg and svelte encode text differently. svg place glyphs individually while svglite place lines as a whole (improving post edits etc)... As for Word, my guess is that it doesn't understand the textLength and lengthAdjust attributes
